version: "3"
services:
  db:
    container_name: servi_db
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./scripts:/usr/src
      - ./.env:/usr/src/.env  
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - "${POSTGRES_PORT}:5342"
  app:
    container_name: servi_app
    restart: always
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
    ports:
      - "${DJANGO_APP_PORT}:8000"
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/data
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  nginx:
    container_name: servi_nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/home/static
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - app