version: "3"
services:
  db:
    container_name: servi_db
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./scripts:/usr/src
      - ./.env:/usr/src/.env  
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - "${POSTGRES_PORT}:5432"
  app:
    container_name: servi_app
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
    ports:
      - "${DJANGO_APP_PORT}:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db