# Generated by Django 3.1.7 on 2022-05-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjugue',
            name='conjugue_form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conjugue_form', to='core.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juntadiscipulado',
            name='junta_discipulado_form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='junta_discipulado_form', to='core.pessoa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='juntadiscipulado',
            unique_together={('junta_discipulado_form', 'junta_discipulado')},
        ),
    ]
