# Generated by Django 3.1.7 on 2022-05-28 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='discipuladores',
            field=models.ManyToManyField(blank=True, related_name='_pessoa_discipuladores_+', to=settings.AUTH_USER_MODEL, verbose_name='Discipuladores'),
        ),
    ]
