# Generated by Django 3.1.7 on 2022-05-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'verbose_name': 'estado civil', 'verbose_name_plural': 'estados civis'},
        ),
        migrations.AlterModelOptions(
            name='nivelservico',
            options={'verbose_name': 'Niveis dos serviços'},
        ),
        migrations.AlterModelOptions(
            name='origemdiscipulo',
            options={'verbose_name': 'Origens dos discípulos'},
        ),
    ]
