# Generated by Django 3.1.7 on 2022-05-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjugue',
            name='conjugue',
        ),
        migrations.AddField(
            model_name='conjugue',
            name='esposa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='esposa', to='core.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conjugue',
            name='marido',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marido', to='core.pessoa'),
            preserve_default=False,
        ),
    ]
