# Generated by Django 3.1.7 on 2022-05-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nivel',
            new_name='nivel_servico',
        ),
    ]
